Repository nail-dp-dev/nail-dp-dev-nextjs14, pull requests merged in 2024-09, with the labels that each got.

#122 [FEAT] 사용자 검색 상세로직 추가, 게시물 해시태그 클릭시 라우팅, 검색결과 페이지 무한스트롤 적용, 하트 클릭 시 좋아요 게시물만 필터링
  api/search/getSearch.ts
  app/(root)/(menubar-exist)/post/[postId]/components/MidContainer.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/bot/ChattingBar.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/mid/PostTags.tsx
  app/(root)/(menubar-exist)/post/[postId]/page.tsx
  app/(root)/(menubar-exist)/post/create/page.tsx
  app/(root)/(menubar-exist)/search/posts/layout.tsx
  app/(root)/(menubar-exist)/search/posts/page.tsx
  app/(root)/layout.tsx
  components/animations/LoadingSpinner.tsx
  components/bars/TagBar.tsx
  components/bars/search/SearchBar.tsx
  components/bars/search/SearchNickname.tsx
  components/bars/search/SearchRecent.tsx
  components/bars/search/SearchWord.tsx
  components/boxes/ArchiveBox.tsx
  components/boxes/PostBox.tsx
  components/buttons/option-menu/GeneralAction.tsx
  components/buttons/option-menu/GeneralShareMenu.tsx
  components/notice/SearchNotice.tsx
  components/ui/ShareMenuList.tsx
  components/ui/UserImage.tsx
  constants/index.ts
  constants/interface.ts
  hooks/useHandleShareCount.ts
  public/assets/gif/loading-gif.gif
  public/assets/gif/loading.gif
  types/dataType.ts
Labels: chore, error

#125 [FEAT] 프로필 페이지 구현 프로필 아카이브 상세 페이지 구현중
  api/archive/getArchiveSelectData.ts
  api/profile/getProfileArchive.ts
  api/profile/getProfilePost.ts
  app/(root)/(menubar-exist)/my-page/page.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/TopContainer.tsx
  app/(root)/(menubar-exist)/profile/[nickname]/page.tsx
  app/(root)/(menubar-exist)/profile/archive/[archiveId]/layout.tsx
  app/(root)/(menubar-exist)/profile/archive/[archiveId]/page.tsx
  app/(root)/(menubar-exist)/profile/archive/[userId]/page.tsx
  constants/index.ts
  constants/interface.ts
  public/assets/img/privateArchive.png
  public/assets/svg/less-than.svg
Labels: chore

#126 [REFACTOR] 프로필 페이지 무한스크롤 및 보인 프로필 마이 페이지로 이동 해결
  api/archive/getArchiveSelectData.ts
  app/(root)/(menubar-exist)/my-page/layout.tsx
  app/(root)/(menubar-exist)/my-page/page.tsx
  app/(root)/(menubar-exist)/post/create/layout.tsx
  app/(root)/(menubar-exist)/post/edit/[postid]/layout.tsx
  app/(root)/(menubar-exist)/profile/[nickname]/layout.tsx
  app/(root)/(menubar-exist)/profile/[nickname]/page.tsx
  app/(root)/(menubar-exist)/profile/archive/[archiveId]/layout.tsx
  app/(root)/(menubar-exist)/profile/archive/[archiveId]/page.tsx
  constants/index.ts
Labels: chore

#127 [REFACTOR] 구글, 네이버 회원가입 연동 완료, 회원가입 완료시 바로 로그인 가능하게끔 구현 완료, 이전에 로그인한 플랫폼 알려주는 아이콘 연동 완료
  api/auth/code/getGoogleAuthCode.ts
  api/auth/code/getKakaoAuthCode.ts
  api/auth/code/getNaverAuthCode.ts
  app/(root)/auth/google/page.tsx
  app/(root)/auth/kakao/page.tsx
  app/(root)/auth/naver/page.tsx
  components/buttons/Toggle.tsx
  components/modal/common/loginModal/LoginModal.tsx
  next.config.mjs
  public/assets/svg/menu-toggle.svg
  store/providers/LoggedInProvider.tsx
Labels: bug, duplicate, chore

#131 [FIX] archive 이미지 불러오지 못하던 에러 해결
  app/(root)/(menubar-exist)/my-page/page.tsx
  components/boxes/ArchiveBox.tsx
Labels: chore

#133 [FIX] list 형일때 생기는 문제 해결
  components/boxes/ArchiveBox.tsx
Labels: bug, error

#135 refactor: 아카이브 메뉴 에러 해결, 마이페이지 토글 활성화, 카테고리바 수정
  app/(root)/(menubar-exist)/my-page/page.tsx
  components/animations/PlusButton.tsx
  components/bars/search/SearchBar.tsx
  components/modal/common/myArchiveModal/MyArchiveModal.tsx
Labels: chore

#137 [REFACTOR] 게시글 수정 버튼수정, postBox router 경로 수정
  app/(root)/(menubar-exist)/post/edit/[postid]/page.tsx
  app/(root)/layout.tsx
  components/modal/common/myArchiveModal/MyArchiveModal.tsx
  public/assets/svg/input_clear.svg
Labels: chore

#138 [FEAT] 중복 검색어 클릭 X, 마지막 태그에 대해서만 에러 메세지 / [STYLE] 검색바 및 디테일게시물 반응형, 댓글 영역 넓이 조정, 댓글Wrap 영역안에서 스크롤
  app/(root)/(menubar-exist)/post/[postId]/components/MidContainer.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/TopContainer.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/mid/CommentItem.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/mid/CommentWrap.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/mid/ReplyItem.tsx
  app/globals.css
  components/bars/search/SearchBar.tsx
  components/bars/search/SearchWord.tsx
  components/boxes/LoginInfoBox.tsx
  components/boxes/PostBox.tsx
  hooks/useGoToProfile.ts
  public/assets/svg/edit-profile-pencil.svg
Labels: chore

#140 [FEAT][CHORE] PostBox 및 디테일 게시물에 대한 기능 개선 및 UI 업데이트
  app/(root)/(menubar-exist)/post/[postId]/components/BotContainer.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/ImageSlider.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/MidContainer.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/bot/ChattingBar.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/icons/PostHeartFillIcon.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/icons/PostHeartIcon.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/icons/ThumbsUpIcon.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/mid/CommentItem.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/mid/CommentWrap.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/mid/PostCount.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/mid/ThumbsUpCount.tsx
  app/(root)/(menubar-exist)/post/[postId]/page.tsx
  components/animations/PlusButton.tsx
  components/boxes/PostBox.tsx
  components/ui/UserImage.tsx
  constants/interface.ts
  public/assets/svg/arrow-left.svg
Labels: chore

#142 [FEAT] 배포 필요 설정
  DockerFile
  dockerignore
  package.json
  yarn.lock
Labels: chore

#146 [STYLE] z-index 조정 / [FEAT] 미디어 타입 확인 함수 추가, 닉네임 검색할때 검색바에 닉네임 저장 / [REFACTOR] 태그,닉네임 검색 함수 수정
  api/post/getPostSharedCount.ts
  app/(root)/(menubar-exist)/post/[postId]/components/BotContainer.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/mid/PostCount.tsx
  components/bars/search/SearchBar.tsx
  components/bars/search/SearchRecent.tsx
  components/bars/search/SearchWord.tsx
  components/boxes/PostBox.tsx
  components/buttons/PostShareButton.tsx
Labels: chore

#149 [REFACTOR] 사진 최적화 작업 테스트
  api/post/getAllPostsData.ts
  app/(root)/(menubar-exist)/(archive)/page.tsx
  app/layout.tsx
  components/boxes/PostBox.tsx
  components/ui/UserImage.tsx
  constants/index.ts
  fonts/PretendardVariable.woff2
  next.config.mjs
  store/slices/boxLayoutSlice.ts
  tailwind.config.ts
Labels: bug, chore

#150 Develop local
  api/post/getAllPostsData.ts
  api/post/getPostSharedCount.ts
  app/(root)/(menubar-exist)/(archive)/page.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/BotContainer.tsx
  app/(root)/(menubar-exist)/post/[postId]/components/mid/PostCount.tsx
  app/layout.tsx
  components/bars/search/SearchBar.tsx
  components/bars/search/SearchRecent.tsx
  components/bars/search/SearchWord.tsx
  components/boxes/PostBox.tsx
  components/buttons/PostShareButton.tsx
  components/buttons/RecentButton.tsx
  components/ui/UserImage.tsx
  constants/index.ts
  fonts/PretendardVariable.woff2
  next.config.mjs
  store/slices/boxLayoutSlice.ts
  tailwind.config.ts
Labels: chore

#153 Develop local
  app/layout.tsx
  components/boxes/PostBox.tsx
  fonts/PretendardVariable.woff2
Labels: bug
