Repository nail-dp-dev/nail-dp-dev-nextjs14, pull requests merged in 2024-06, with the labels that each got.

#15 [DOCS] README.md 초기 작성 완료.
  README.md
Labels: documentation

#20 Update README.md
  README.md
Labels: documentation

#21 Update README.md
  README.md
Labels: documentation

#22 Update README.md
  README.md
Labels: documentation

#32 [FEAT] 메인 검색 input 일부 구현
  app/layout.tsx
  components/bars/SearchBar.tsx
  public/assets/svg/close.svg
  public/assets/svg/search.svg
  tailwind.config.ts
Labels: chore

#33 [FEAT] menubar 구현 완료
  app/globals.css
  app/layout.tsx
  components/bars/MenuBar.tsx
  components/boxes/LoginInfoBox.tsx
  components/buttons/MenuButton.tsx
  constants/example/index.ts
  constants/index.ts
  next.config.mjs
  public/assets/svg/bits.svg
  public/assets/svg/buy.svg
  public/assets/svg/design.svg
  public/assets/svg/home.svg
  public/assets/svg/my-archive.svg
  public/assets/svg/my-page.svg
  public/assets/svg/reservation.svg
  public/assets/svg/setting.svg
Labels: chore

#37 [FEAT] 다크모드 구현
  app/layout.tsx
  app/setting/components/ThemeToggle.tsx
  app/setting/page.tsx
  components/bars/MenuBar.tsx
  store/store.ts
  store/themeSlice.ts
  tailwind.config.ts
Labels: chore

#39 [REFACTOR] app router 내 파일구조 변경
  app/(archive)/layout.tsx
  app/(home)/(archive)/(for-you)/page.tsx
  app/(home)/(archive)/components/CategoryBar.tsx
  app/(home)/(archive)/new/page.tsx
  app/(home)/(archive)/trending/page.tsx
  app/(home)/buy/layout.tsx
  app/(home)/buy/page.tsx
  app/(home)/design/layout.tsx
  app/(home)/design/page.tsx
  app/(home)/layout.tsx
  app/(home)/my-archive/layout.tsx
  app/(home)/my-archive/page.tsx
  app/(home)/my-page/layout.tsx
  app/(home)/my-page/page.tsx
  app/(home)/reservation/layout.tsx
  app/(home)/reservation/page.tsx
  app/(home)/setting/components/ThemeToggle.tsx
  app/(home)/setting/layout.tsx
  app/(home)/setting/page.tsx
  app/error.tsx
  app/layout.tsx
  app/not-found.tsx
  components/bars/MenuBar.tsx
  constants/endpoints.ts
  constants/urls.ts
  store/slice.ts
  store/store.ts
Labels: bug, invalid

#40 [REFACTOR] Layout 3중 구조로 변경
  app/(home)/(archive)/layout.tsx
  app/(home)/buy/layout.tsx
  app/(home)/design/layout.tsx
  app/(home)/layout.tsx
  app/(home)/my-archive/layout.tsx
  app/(home)/my-page/layout.tsx
  app/(home)/reservation/layout.tsx
  app/layout.tsx
  components/bars/CategoryBar.tsx
  constants/urls.ts
  package.json
  yarn.lock
Labels: chore

#41 [Feat] 플러스 아이콘, 하트 아이콘 애니메이션 구현
  components/buttons/HeartButton.tsx
  components/buttons/PlusButton.tsx
  public/assets/svg/heart.svg
Labels: chore

#42 chore : yarn framer-motion 설치
  components/buttons/HeartButton.tsx
  package.json
  yarn.lock
Labels: chore

#44 [CONF] prettierrc 설정
  .prettierrc.json
  package.json
  tailwind.config.ts
  yarn.lock
Labels: chore

#45 [REFACTOR] Menu button component 화의 Error occured 로 인하여 구조 재 배치화
  app/(home)/(archive)/(for-you)/new/page.tsx
  app/(home)/(archive)/(for-you)/page.tsx
  app/(home)/(archive)/(for-you)/trending/page.tsx
  app/(home)/(archive)/layout.tsx
  app/(home)/setting/components/ThemeToggle.tsx
  app/globals.css
  components/bars/CategoryBar.tsx
  components/bars/MenuBar.tsx
  components/boxes/LoginInfoBox.tsx
  components/buttons/MenuButton.tsx
  constants/index.ts
  constants/interface.ts
  public/assets/svg/minus.svg
  public/assets/svg/plus.svg
  store/slice/loginSlice.ts
  store/slice/themeSlice.ts
  store/store.ts
Labels: bug, chore

#46 [FEAT] errorpage 일부 구현
  app/globals.css
  app/not-found.tsx
  components/animations/NailMoving.tsx
  components/bars/SearchBar.tsx
  public/assets/svg/nail-logo.svg
  tailwind.config.ts
Labels: chore

#49 [FEAT] errorpage 반응형 적용 및 아이콘 애니메이션 구현
  app/not-found.tsx
  components/animations/NailMoving.tsx
  tailwind.config.ts
Labels: chore

#50 [FEAT] Landing page 아카이브 페이지의 3가지 카테고리 임시 구현 및 게시글 이미지 창 사이즈3 가변 기능 구현
  app/(home)/(archive)/(for-you)/new/page.tsx
  app/(home)/(archive)/(for-you)/page.tsx
  app/(home)/(archive)/(for-you)/trending/page.tsx
  app/(home)/(archive)/@modal/page.tsx
  app/(home)/(archive)/layout.tsx
  app/(home)/layout.tsx
  app/globals.css
  app/layout.tsx
  components/animations/HeartButton.tsx
  components/bars/CategoryBar.tsx
  components/bars/SearchBar.tsx
  components/boxes/PostBox.tsx
  constants/example/index.ts
  constants/index.ts
  constants/interface.ts
  next.config.mjs
  store/slice/boxLayoutSlice.ts
  store/store.ts
  tailwind.config.ts
Labels: bug, chore, error

#51 [REFACTOR] 하트아이콘 플러스 아이콘 상태 변경 기능 추가
  components/animations/HeartButton.tsx
  components/animations/PlusButton.tsx
  constants/interface.ts
Labels: chore

#52 [REFACTOR] : 플러스 아이콘 사이즈 변경 기능 추가
  components/animations/HeartButton.tsx
  components/animations/PlusButton.tsx
  components/boxes/PostBox.tsx
  constants/interface.ts
Labels: chore

#55 [FEAT] landing page의 mini 모달 구현
  app/(home)/(archive)/(for-you)/page.tsx
  app/(home)/(archive)/@modal/default.tsx
  app/(home)/(archive)/@modal/page.tsx
  app/(home)/(archive)/layout.tsx
  app/loading.tsx
  components/bars/CategoryBar.tsx
  components/bars/MenuBar.tsx
  components/boxes/LoginInfoBox.tsx
  components/buttons/MenuButton.tsx
  components/modal/mini/LoginSuggestModal.tsx
  components/modal/mini/ProfileMiniModal.tsx
  constants/example/index.ts
  constants/index.ts
  constants/interface.ts
  public/assets/img/etcProfileImage.png
  public/assets/svg/thin-plus.svg
  tailwind.config.ts
Labels: chore

#56 [REFACTOR] Landing page 기획 변경 및 svg fill color change
  app/(home)/(archive)/(for-you)/new/page.tsx
  app/(home)/(archive)/(for-you)/trending/page.tsx
  app/(home)/(archive)/(page)/page.tsx
  app/(home)/(archive)/layout.tsx
  components/bars/CategoryBar.tsx
  components/boxes/PostBox.tsx
  components/buttons/MenuButton.tsx
  constants/example/index.ts
  constants/index.ts
  constants/interface.ts
Labels: chore

#57 [REFACTOR] Category 삭제 건 복구
  app/(home)/(archive)/(for-you)/new/page.tsx
  app/(home)/(archive)/(for-you)/page.tsx
  app/(home)/(archive)/(for-you)/trending/page.tsx
  app/(home)/(archive)/layout.tsx
  components/bars/CategoryBar.tsx
  constants/interface.ts
Labels: invalid, chore

#58 [STYLE] 공통 레이아웃 및 색상 등 globals.css에 추가
  app/(home)/setting/page.tsx
  app/globals.css
  tailwind.config.ts
Labels: chore

#59 [STYLE] input창과 dropdown 위치 조정, [FEAT] close 기능 추가
  app/(home)/(archive)/layout.tsx
  components/bars/SearchBar.tsx
  components/bars/mainSearch/SearchBar.tsx
  components/bars/mainSearch/SearchHistory.tsx
  components/buttons/HistoryButton.tsx
  public/assets/svg/small-close.svg
Labels: chore

#61 [FEAT] Message 팝업 아이콘 및 Chat modal 초기 구현 완료
  api/getUserData.ts
  app/(home)/(archive)/(for-you)/new/page.tsx
  app/(home)/(archive)/(for-you)/page.tsx
  app/(home)/(archive)/(for-you)/trending/page.tsx
  app/(home)/(archive)/@modal/default.tsx
  app/(home)/(archive)/@modal/page.tsx
  app/(root)/(archive)/(category)/(for-you)/page.tsx
  app/(root)/(archive)/(category)/new/page.tsx
  app/(root)/(archive)/(category)/trending/page.tsx
  app/(root)/(archive)/layout.tsx
  app/(root)/buy/layout.tsx
  app/(root)/buy/page.tsx
  app/(root)/design/layout.tsx
  app/(root)/design/page.tsx
  app/(root)/layout.tsx
  app/(root)/my-archive/layout.tsx
  app/(root)/my-archive/page.tsx
  app/(root)/my-page/components/CreatePost.tsx
  app/(root)/my-page/layout.tsx
  app/(root)/my-page/page.tsx
  app/(root)/reservation/layout.tsx
  app/(root)/reservation/page.tsx
  app/(root)/setting/components/ThemeToggle.tsx
  app/(root)/setting/layout.tsx
  app/(root)/setting/page.tsx
  app/globals.css
  app/layout.tsx
  app/loading.tsx
  components/boxes/ChattingBox.tsx
  components/boxes/LoginInfoBox.tsx
  components/modal/message/MessageModal.tsx
  constants/index.ts
  constants/interface.ts
  hooks/useUserData.ts
  package.json
  public/assets/svg/chat.svg
  public/assets/svg/close_chat.svg
  public/assets/svg/close_chat_max.svg
  tailwind.config.ts
  types/dataType.ts
  yarn.lock
Labels: bug, chore, error

#62 [FIX] Message Modal 로 인한 height 오류 해결
  app/(root)/layout.tsx
  app/globals.css
  components/boxes/ChattingBox.tsx
  components/modal/message/MessageModal.tsx
  constants/example/index.ts
  public/assets/svg/small-search.svg
  tailwind.config.ts
Labels: bug

#63 [REFACTOR] profile를 boxes로 이동
  components/boxes/ProfileBox.tsx
Labels: chore

#64 [REFACTOR] mypage layout 수정
  app/(root)/my-page/layout.tsx
Labels: chore

#65 [FEAT] Login modal 완료
  app/(root)/layout.tsx
  components/boxes/ChattingBox.tsx
  components/modal/common/commonModalLayout.tsx
  components/modal/common/loginModal/LoginModal.tsx
  components/modal/message/MessageModal.tsx
  components/modal/mini/LoginSuggestModal.tsx
  constants/index.ts
  public/assets/svg/google.svg
  public/assets/svg/kakao.svg
  public/assets/svg/naver.svg
  public/assets/svg/small-logo.svg
  public/assets/svg/used_login_platform.svg
  store/slice/modalSlice.ts
  store/store.ts
  tailwind.config.ts
Labels: chore

#66 [FEAT] 추천 검색어, 팔로우 영역 배치, [CHORE] 폴더 구조 변경
  app/(root)/(archive)/layout.tsx
  app/(root)/my-page/layout.tsx
  app/(root)/setting/page.tsx
  components/bars/search/SearchBar.tsx
  components/bars/search/SearchFollow.tsx
  components/bars/search/SearchHistory.tsx
  components/bars/search/SearchWord.tsx
  components/boxes/LoginInfoBox.tsx
  constants/example/index.ts
  types/dataType.ts
Labels: chore

#68 [FEAT] SignUp page 초기 구현 완료
  app/(root)/(archive)/(category)/(for-you)/page.tsx
  app/(root)/sign-up/(agreement)/(page)/default.tsx
  app/(root)/sign-up/(agreement)/(page)/page.tsx
  app/(root)/sign-up/(agreement)/@modal/default.tsx
  app/(root)/sign-up/(agreement)/@modal/page.tsx
  app/(root)/sign-up/(agreement)/layout.tsx
  app/(root)/sign-up/components/TopBar.tsx
  app/(root)/sign-up/layout.tsx
  app/(root)/sign-up/nickname/(page)/page.tsx
  app/(root)/sign-up/nickname/@modal/page.tsx
  app/(root)/sign-up/nickname/layout.tsx
  app/(root)/sign-up/phone/(page)/page.tsx
  app/(root)/sign-up/phone/@modal/default.tsx
  app/(root)/sign-up/phone/@modal/page.tsx
  app/(root)/sign-up/phone/layout.tsx
  components/boxes/PostBox.tsx
  components/modal/common/loginModal/LoginModal.tsx
  constants/index.ts
  lib/utils.ts
  public/assets/svg/middle-logo.svg
Labels: chore

#71 [REFACTOR] 회원가입 페이지의 kakao 인가코드 테스트
  app/(root)/sign-up/(agreement)/(page)/page.tsx
  app/(root)/sign-up/nickname/(page)/page.tsx
  app/(root)/sign-up/nickname/@modal/page.tsx
  app/(root)/sign-up/nickname/layout.tsx
  constants/index.ts
Labels: chore

#72 [REFACTOR] 회원가입 페이지 중 카카오 redirect uri 숨김처리
  .gitignore
  app/(root)/auth/page.tsx
  app/(root)/sign-up/(agreement)/(page)/default.tsx
  app/(root)/sign-up/(agreement)/@modal/default.tsx
  app/(root)/sign-up/(agreement)/@modal/page.tsx
  app/(root)/sign-up/(agreement)/layout.tsx
  app/(root)/sign-up/components/ProcedureInfoBox.tsx
  app/(root)/sign-up/components/TopBar.tsx
  app/(root)/sign-up/components/procedures/Agreement.tsx
  app/(root)/sign-up/layout.tsx
  app/(root)/sign-up/page.tsx
  app/(root)/sign-up/phone/(page)/page.tsx
  app/(root)/sign-up/phone/@modal/default.tsx
  app/(root)/sign-up/phone/@modal/page.tsx
  app/(root)/sign-up/phone/layout.tsx
  app/layout.tsx
  components/modal/common/commonModalLayout.tsx
  components/modal/common/loginModal/LoginModal.tsx
  components/modal/message/MessageModal.tsx
  components/modal/mini/LoginSuggestModal.tsx
  constants/index.ts
  next.config.mjs
  package.json
  public/assets/svg/big-logo.svg
  public/assets/svg/procedure_circle.svg
  public/assets/svg/procedure_heart.svg
  store/CommonModalProvider.tsx
  store/slice/modalSlice.ts
  yarn.lock
Labels: duplicate, help wanted

#73 [FIX] KAKAO 관련 문제 해결완료
  api/getUserData.ts
  app/(root)/auth/page.tsx
  app/(root)/sign-up/components/procedures/Agreement.tsx
  app/(root)/sign-up/layout.tsx
  public/assets/svg/check.svg
  tailwind.config.ts
Labels: chore

#74 [FEAT] 유저 프로필 공통UI 컴포넌트 제작
  components/bars/search/SearchFollow.tsx
  components/bars/search/SearchWord.tsx
  components/ui/UserImage.tsx
  components/ui/UserInfo.tsx
Labels: chore

#76 [FEAT] Agreement, Phone modal 초기 구현 완료 [REFACTOR] KAKAO 관련 로그인 세팅 문제 구조 변경 [FIX] 카카오 간편로그인 관련 해결
  app/(root)/auth/google/page.tsx
  app/(root)/auth/kakao/page.tsx
  app/(root)/auth/naver/page.tsx
  app/(root)/sign-up/components/ProcedureInfoBox.tsx
  app/(root)/sign-up/components/procedures/Agreement.tsx
  app/(root)/sign-up/components/procedures/NickNameValidation.tsx
  app/(root)/sign-up/components/procedures/PhoneNumberValidation.tsx
  app/(root)/sign-up/page.tsx
  constants/index.ts
  constants/interface.ts
  public/assets/svg/procedure_info.svg
  public/assets/svg/procedure_phone.svg
  tailwind.config.ts
  types/dataType.ts
Labels: bug, duplicate, chore, error, sub task
