Repository nail-dp-dev/nail-dp-dev-nextjs14, pull requests merged in 2024-07, with the labels that each got.

#77 [STYLE] closeIcon hover, active시 스타일링, [FIX] layout, objectFIt 콘솔 경고 해결 / 태그 x버튼 누를 시 드롭다운과 같이 닫히는 현상 해결
  components/bars/search/SearchBar.tsx
  components/bars/search/SearchHistory.tsx
  components/buttons/HistoryButton.tsx
  components/ui/UserImage.tsx
Labels: bug, chore

#78 [FEAT] Nickname 모달 구현 완료. [REFACTOR] Auth 페이지에서 routing 되는 부분 변경 [FIX] forbidden words의 코드를 노출시키는 부분을 변경
  api/auth/getGoogleAuthCode.ts
  api/auth/getKakaoAuthCode.ts
  api/auth/getNaverAuthCode.ts
  api/getUserData.ts
  api/post/getPostsData.ts
  api/post/getPostsLikedData.ts
  api/user/getUserData.ts
  app/(root)/(archive)/(category)/(for-you)/page.tsx
  app/(root)/(archive)/(category)/new/page.tsx
  app/(root)/(archive)/(category)/trending/page.tsx
  app/(root)/auth/google/page.tsx
  app/(root)/auth/kakao/page.tsx
  app/(root)/auth/naver/page.tsx
  app/(root)/sign-up/components/ProcedureInfoBox.tsx
  app/(root)/sign-up/components/ProcedureNumber.tsx
  app/(root)/sign-up/components/TopBar.tsx
  app/(root)/sign-up/components/procedures/Agreement.tsx
  app/(root)/sign-up/components/procedures/NickNameValidation.tsx
  app/(root)/sign-up/page.tsx
  app/globals.css
  components/animations/PostCreateIcon.tsx
  components/boxes/PostBox.tsx
  components/modal/common/loginModal/LoginModal.tsx
  constants/example/index.ts
  constants/index.ts
  constants/interface.ts
  hooks/useUserData.ts
  public/assets/svg/procedure_circle.svg
  public/assets/svg/procedure_heart.svg
  tailwind.config.ts
  types/dataType.ts
Labels: chore, task

#79 [FEAT] 스크롤 기능 구현 완료. [REFACTOR] 프로필 구조 변경, [CHORE] tailwind-scrollbar-hide 설치
  app/(root)/my-page/page.tsx
  components/buttons/ProfileButton.tsx
  constants/example/index.ts
  constants/interface.ts
  package.json
  tailwind.config.ts
  yarn.lock
Labels: chore

#81 [FIX] 애니메이션 아이콘 초기상태 이상 해결
  components/animations/PlusButton.tsx
  components/animations/PostCreateIcon.tsx
Labels: bug

#82 [FEAT] 검색 기능 구현 완료, [CONF] tailwind 플러그인 추가, [CHORE] 파일 이름 변경
  .prettierrc.json
  app/globals.css
  components/bars/search/SearchBar.tsx
  components/bars/search/SearchFollow.tsx
  components/bars/search/SearchHistory.tsx
  components/bars/search/SearchRecent.tsx
  components/bars/search/SearchWord.tsx
  components/buttons/HistoryButton.tsx
  components/buttons/RecentButton.tsx
  package.json
  yarn.lock
Labels: chore

#84 [FEAT] SignUp page 구현 완료 (카카오). [REFACTOR] 회원가입 및 로직 구현시에 백엔드와의 협업 부분 협의 및 협력 강화.
  api/auth/getGoogleAuthCode.ts
  api/auth/getIsNIckNameExist.ts
  api/auth/getKakaoAuthCode.ts
  api/auth/getNaverAuthCode.ts
  api/auth/postSignUpMember.ts
  api/post/getPostsData.ts
  api/post/getPostsLikedData.ts
  api/user/getUserData.ts
  app/(root)/buy/page.tsx
  app/(root)/design/page.tsx
  app/(root)/my-archive/page.tsx
  app/(root)/my-page/page.tsx
  app/(root)/reservation/page.tsx
  app/(root)/setting/page.tsx
  app/(root)/sign-up/components/procedures/Agreement.tsx
  app/(root)/sign-up/components/procedures/NickNameValidation.tsx
  app/(root)/sign-up/components/procedures/PhoneNumberValidation.tsx
  app/(root)/sign-up/page.tsx
  components/modal/message/MessageModal.tsx
  constants/interface.ts
  types/dataType.ts
Labels: documentation, chore, sub task

#85 [FEAT] 틀 구조 일부 구현, [CHORE] 임시 데이터 추가 및 적용
  api/post/getPostsDetailData.ts
  app/(root)/post/[postId]/components/BotContainer.tsx
  app/(root)/post/[postId]/components/MidContainer.tsx
  app/(root)/post/[postId]/components/TopContainer.tsx
  app/(root)/post/[postId]/layout.tsx
  app/(root)/post/[postId]/page.tsx
  components/bars/search/SearchFollow.tsx
  components/bars/search/SearchWord.tsx
  components/boxes/ProfileBox.tsx
  components/ui/UserInfo.tsx
  constants/example/index.ts
  constants/interface.ts
  hooks/useUser.ts
  types/dataType.ts
Labels: chore

#87 [Feat] 공개 범위설정, 요청 api 작성 [REFACTOR] 게시판 작성 ui 수정 및 기능 수정
  api/post/postCreate.ts
  api/post/tempPostCreate.ts
  app/(root)/my-page/page.tsx
  app/(root)/post/create/components/ContentContainer.tsx
  app/(root)/post/create/components/HashTagContainer.tsx
  app/(root)/post/create/components/ImageUplodeContainer.tsx
  app/(root)/post/create/components/PrivacySettingContainer.tsx
  app/(root)/post/create/layout.tsx
  app/(root)/post/create/page.tsx
  public/assets/svg/hashtag-arrow.svg
  types/dataType.ts
Labels: chore

#89 [REFACTOR] 요청 api 데이터 구조 수정, [FIX] 태그 버튼 색변경, useRouter 에러 수정
  api/post/postCreate.ts
  api/post/tempPostCreate.ts
  app/(root)/post/create/components/HashTagContainer.tsx
  app/(root)/post/create/components/ImageUploadContainer.tsx
  app/(root)/post/create/page.tsx
  public/assets/svg/image-upload-plus.svg
Labels: chore

#90 [FEAT] postdetailpage 틀 일부 구현
  api/post/getCommentsDetailData.ts
  api/post/getPostsDetailData.ts
  app/(root)/post/[postId]/components/Bot/ChattingBar.tsx
  app/(root)/post/[postId]/components/BotContainer.tsx
  app/(root)/post/[postId]/components/MidContainer.tsx
  app/(root)/post/[postId]/components/TopContainer.tsx
  app/(root)/post/[postId]/components/icons/PostChatIcon.tsx
  app/(root)/post/[postId]/components/icons/PostHeartIcon.tsx
  app/(root)/post/[postId]/components/icons/PostShareIcon.tsx
  app/(root)/post/[postId]/components/icons/ThumbsUpIcon.tsx
  app/(root)/post/[postId]/components/mid/ChattingBox.tsx
  app/(root)/post/[postId]/components/mid/PostCount.tsx
  app/(root)/post/[postId]/components/mid/PostTags.tsx
  app/(root)/post/[postId]/page.tsx
  app/globals.css
  components/buttons/Toggle.tsx
  constants/example/index.ts
  constants/index.ts
  hooks/usePostDetail.ts
  hooks/useUser.ts
  public/assets/svg/Thumbs-up.svg
  public/assets/svg/emoticon.svg
  public/assets/svg/menu-toggle.svg
  public/assets/svg/post-chat.svg
  public/assets/svg/post-heart.svg
  public/assets/svg/post-share.svg
  types/dataType.ts
Labels: chore

#91 [FIX] 랜딩 페이지 첫 렌더링 시 깜빡이는 문제 헤결 [FIX] Backend logout test 완료 [REFACTOR] Redux login status type 변경
  api/auth/getLogOut.ts
  app/(root)/sign-up/components/procedures/NickNameValidation.tsx
  components/boxes/LoginInfoBox.tsx
  components/modal/message/MessageModal.tsx
  components/modal/mini/LoginSuggestModal.tsx
  store/LoggedInProvider.tsx
  store/slice/loginSlice.ts
Labels: bug, chore, error

#92 [REFACTOR] 게시글 작성 api 요청 수정
  api/post/postCreate.ts
  api/post/tempPostCreate.ts
  app/(root)/post/create/page.tsx
Labels: chore

#93 [FEAT] NEW 조회 API 연결 완료. [TEST] NEW 조회 API 백엔드 테스트 완료.
  api/auth/code/getGoogleAuthCode.ts
  api/auth/code/getKakaoAuthCode.ts
  api/auth/code/getNaverAuthCode.ts
  api/auth/helper/getIsNIckNameExist.ts
  api/auth/secure/getLogOut.ts
  api/auth/secure/postSignUpMember.ts
  api/post/getAllPostsData.ts
  api/post/getPostsData.ts
  api/user/getUserData.ts
  app/(root)/(archive)/(category)/(for-you)/loading.tsx
  app/(root)/(archive)/(category)/(for-you)/page.tsx
  app/(root)/(archive)/(category)/new/page.tsx
  app/(root)/(archive)/(category)/trending/page.tsx
  app/(root)/(archive)/layout.tsx
  app/(root)/my-page/page.tsx
  app/(root)/sign-up/components/procedures/NickNameValidation.tsx
  app/globals.css
  app/layout.tsx
  components/bars/CategoryBar.tsx
  components/bars/MenuBar.tsx
  components/boxes/LoginInfoBox.tsx
  components/boxes/PostBox.tsx
  components/boxes/PostsBox.tsx
  components/buttons/MenuButton.tsx
  components/modal/common/loginModal/LoginModal.tsx
  components/ui/UserInfo.tsx
  constants/index.ts
  constants/interface.ts
  hooks/useAllPosts.ts
  hooks/useUserData.ts
  next.config.mjs
  tailwind.config.ts
  types/dataType.ts
Labels: bug, duplicate, chore

#96 [FEAT] 게시글 수정 기능 및 api 요청 구현
  api/post/getPostEditData.ts
  api/post/postEdit.ts
  app/(root)/post/create/page.tsx
  app/(root)/post/edit/[postid]/layout.tsx
  app/(root)/post/edit/[postid]/page.tsx
  components/post/ContentContainer.tsx
  components/post/HashTagContainer.tsx
  components/post/ImageUploadContainer.tsx
  components/post/PrivacySettingContainer.tsx
Labels: chore

#97 [REFACTOR] 랜딩페이지 API 관련 리팩토링
  api/post/getAllPostsData.ts
  api/user/getUserData.ts
  app/(root)/(archive)/(category)/(for-you)/loading.tsx
  components/boxes/LoginInfoBox.tsx
  components/boxes/PostBox.tsx
  components/boxes/PostsBox.tsx
  components/modal/common/commonModalLayout.tsx
  components/ui/Video.tsx
  constants/index.ts
  constants/interface.ts
  hooks/auth/useLoggedInUserData.ts
  hooks/post/useAllPosts.ts
  hooks/useUserData.ts
  next.config.mjs
  types/dataType.ts
Labels: documentation, chore

#98 [FEAT] 게시물 댓글/대댓글 구현 완료
  api/post/getCommentsDetailData.ts
  api/post/getPostsData.ts
  api/post/getRepliesDetailData.tsx
  api/user/getUserData.ts
  app/(root)/post/[postId]/components/Bot/ChattingBar.tsx
  app/(root)/post/[postId]/components/Bot/ReplyBar.tsx
  app/(root)/post/[postId]/components/BotContainer.tsx
  app/(root)/post/[postId]/components/CommentOptions.tsx
  app/(root)/post/[postId]/components/DeleteModal.tsx
  app/(root)/post/[postId]/components/MidContainer.tsx
  app/(root)/post/[postId]/components/TopContainer.tsx
  app/(root)/post/[postId]/components/icons/PostChatIcon.tsx
  app/(root)/post/[postId]/components/icons/PostHeartFillIcon.tsx
  app/(root)/post/[postId]/components/icons/PostToggleIcon.tsx
  app/(root)/post/[postId]/components/icons/ReplyIcon.tsx
  app/(root)/post/[postId]/components/icons/ThumbsUpIcon.tsx
  app/(root)/post/[postId]/components/mid/ChattingBox.tsx
  app/(root)/post/[postId]/components/mid/CommentItem.tsx
  app/(root)/post/[postId]/components/mid/CommentWrap.tsx
  app/(root)/post/[postId]/components/mid/PostCount.tsx
  app/(root)/post/[postId]/components/mid/PostTags.tsx
  app/(root)/post/[postId]/components/mid/ReplyItem.tsx
  app/(root)/post/[postId]/components/mid/ThumbsUpCount.tsx
  app/(root)/post/[postId]/page.tsx
  app/globals.css
  components/buttons/Toggle.tsx
  components/modal/common/commonModalLayout.tsx
  components/ui/ConfirmModal.tsx
  components/ui/UserInfo.tsx
  hooks/post/useAllPosts.ts
  hooks/useComments.ts
  hooks/usePostDetail.ts
  lib/formatTimeAgo.ts
  public/assets/svg/post-chat-toggle.svg
  public/assets/svg/post-heart-fill.svg
  public/assets/svg/reply-comment.svg
  store/slice/commentsSlice.ts
  store/slice/replyUserSlice.ts
  store/store.ts
  tailwind.config.ts
  types/dataType.ts
Labels: bug, chore

#99 [FIX] 무한 요청 관련 문제 해결
  components/boxes/PostsBox.tsx
  hooks/post/useAllPosts.ts
Labels: bug, chore, error
